### DISCUSSION TITLE
Also replace/remove the "className=" portion?

### DISCUSSION THREAD

**Discussion by AKRking** [moalamri/vscode-inline-fold#118] [Q&A]
For better readability is it possible to hide/replace the "className=" also?

```
<button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
  Button
</button>
```
becomes this 👇
```
<button ''>
  Button
</button>
```

**Comment by emedeirox** [comment]
@AKRking 
Yes you can change the inlineFold.regexGroup configuration to fold what your don't want so see.
In your case... just put the entire regex inside a group, and change the regex group to 1
Example:
```yaml
{
  "inlineFold.regex": "(className)=(({(`|))|(['\"`]))(.*?)(\\2|(\\4))",
  "inlineFold.regexFlags": "g",
  "inlineFold.regexGroup": 6
}
```
To this:
```yaml
{
  "inlineFold.regex": "((className)=(({(`|))|(['\"`]))(.*?)(\\2|(\\4)))",
  "inlineFold.regexFlags": "g",
  "inlineFold.regexGroup": 1
}
```
This should do the trick, but maybe need some ajustment.
