### ISSUE TITLE
Multiple fold configurations

### ISSUE THREAD

**Issue by emedeirox** [moalamri/vscode-inline-fold#34]
Possibility to add adicional configuration, could be via JSON settings.
### Poll https://github.com/moalamri/vscode-inline-fold/discussions/55

**Comment by moalamri** [comment]
Thanks for the suggestion.
Yes, it will be that way with the next update (which supports language scoped settings), I have not yet estimated when to release it as I have some tight deadline at work, so when I get free time, I will surely work on it :)

**Comment by moalamri** [comment]
@e-medeiros what do you think?
https://github.com/moalamri/vscode-inline-fold/discussions/55

**Comment by mudgalx** [comment]
First of all, Thankyou to provide this extension. I have a suggestion if you could add auto collapsing svg's when adding multiple regex. It would be great.

**Comment by MrFoxPro** [comment]
Waiting for this feature.

**Comment by benjamin-kirkbride** [comment]
Any update for this? Would love to see it happen :)

**Comment by moalamri** [comment]
> Any update for this? Would love to see it happen :)

Hey 
Sure I will work on it when I have time 👍
I’m a bit interested in the use cases for this particular feature, can you give me an example to work on?

**Comment by alexilyaev** [comment]
> > Any update for this? Would love to see it happen :)
> 
> Hey Sure I will work on it when I have time 👍 I’m a bit interested in the use cases for this particular feature, can you give me an example to work on?

Working with Styled-Components, we'd like to fold the CSS blocks, e.g.:

```tsx
const Header = styled.div`
  position: absolute;
  top: 15px;
  left: 110px;
  width: 132px;
  height: 132px;
`;
```

Expected:

```tsx
const Header = styled.div`...`;
```

Doesn't quite fold it at the moment:

<img width="346" alt="image" src="https://github.com/moalamri/vscode-inline-fold/assets/480469/3cfd73a9-4909-444d-bc24-3b45a5541985">

Settings:

```
  "inlineFold.regex": "styled.[a-z]+`([^`]+)`",
  "inlineFold.regexFlags": "gi",
  "inlineFold.regexGroup": 1,
  "inlineFold.unfoldedOpacity": 0.8,
  "inlineFold.maskChar": "...",
  "inlineFold.maskColor": "#FF0000",
  "inlineFold.unfoldOnLineSelect": true,
  "inlineFold.autoFold": true
```

Same thing with SVG:

```
  "inlineFold.regex": "<svg(\\s*.*?\\s*)</svg>",
  "inlineFold.regexFlags": "gs",
  "inlineFold.regexGroup": 1,
```

<img width="798" alt="image" src="https://github.com/moalamri/vscode-inline-fold/assets/480469/5343787a-e1eb-4a8e-8e20-67b5526cedd2">

**Comment by moalamri** [comment]
@alexilyaev I guess the issue title is misleading. 

regarding your request you can find the answer [here ](https://github.com/moalamri/vscode-inline-fold/discussions/69#discussioncomment-4150206)

**Comment by theodopolopodous** [comment]
But it would still be great to have a nicer UI for multiple regex patterns, rather than putting every use-case into one regex

Does it deserve another issue for clarity?

**Comment by e-medeiros** [comment]
@theodopolopodous let me clarify the issue: 
I use this extension as well: https://marketplace.visualstudio.com/items?itemName=Tobermory.es6-string-html 
In its syntaxes folder there some JSON files with some rules for the regex parser.
My idea is to create a field where I can put a JSON, (or choose a JSON file), like this ones. with the regex(es) I want...ClassNames, SVG... so VSCode can fold them.
EXAMPLE:
```yaml
[
    {
      "inlineFold.regex":  "<svg(\\s*.*?\\s*)<\/svg>",
      "inlineFold.regexFlags":  "gs",
      "inlineFold.regexGroup":  1,
      "inlineFold.maskChar":  "*SVG*",
      "inlineFold.maskColor":  "#ADCD09"
    },
    {
      "inlineFold.regex": "\\[([^\\]]*)\\]\\(([^\\s]+)\\)[^\\)\\s]*\\s",
      "inlineFold.regexFlags":  "g",
      "inlineFold.regexGroup":  2,
      "inlineFold.supportedLanguages":  ["markdown"],
      "inlineFold.maskChar":  "*LINK*",
      "inlineFold.maskColor":  "#FFCC09"
    }
]
```
Using one regex would be HELLISH.
@moalamri do you know if possible to use something like this?
